/** @type {import('tailwindcss').Config} */
const plugin = require("tailwindcss/plugin");

module.exports = {
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  theme: {
    fontFamily: {
      main: "Gilroy",
      second: "Gilroy-semibold",
      body: "Benegraphic",
      about: "QuigleyWiggly",
      mainText: "Passion One",
      textSec: "Roboto",
      textBtn: "Poppins",
    },
    extend: {
      backgroundImage: {
        uploadImage: "url('/src/Components/Theme/Img/dots1.png')",
        testimonialBgMb:
          "url('/src/Components/Theme/Img/testimonialBgMob.png')",
        stickerPage1cardMob:
          "url('/src/Components/Theme/Img/mobile/Frame6.png')",
        stickerPage1ModalMob:
          "url('/src/Components/Theme/Img/mobile/Frame6Mob.png')",
        stickerPage2cardMob:
          "url('/src/Components/Theme/Img/mobile/Frame7.png')",
        Frame6: "url('/src/Components/Theme/Img/Frame6.png')",
        samurai: "url('/src/Components/Theme/samurai.png')",
        headImage: "url('/src/Components/Theme/Img/background2.png')",
        variant1: "url('/src/Components/Theme/Img/variant1.png')",
        variant2: "url('/src/Components/Theme/Img/Variant2.png')",
        variant1img: "url('/src/Components/Theme/Img/variant1img.png')",
        variant2img: "url('/src/Components/Theme/Img/variant2img.png')",
        questionImage: "url('/src/Components/Theme/Img/question.png')",
        showcase: "url('/src/Components/Theme/Img/ShowCase.png')",
        showcasemb: "url('/src/Components/Theme/Img/ShowCaseMb.png')",
        testimonials: "url('/src/Components/Theme/Img/Testimonials.png')",
        bgParallax: "url('/src/Components/Theme/Img/Parallax/bg.png')",
        bg2Parallax: "url('/src/Components/Theme/Img/Parallax/bg1.png')",
        treesParallax: "url('/src/Components/Theme/Img/Parallax/trees.png')",
        samuraiParallax:
          "url('/src/Components/Theme/Img/Parallax/samurai.png')",
        mobileBg: "url('/src/Components/Theme/Img/MobileBg.png')",
        blogBg: "url('/src/Components/Theme/Img/blog.png')",
        blogCard:
          "linear-gradient(179.83deg, rgba(45, 6, 27, 0.18) -18.38%, rgba(45, 6, 27, 0.83) 81.1%);",
      },
      colors: {
        "main-color": "#2D061B",
        "text-color": "#433E3E",
        "text-gray": "#C5C3C3",
        regular: "#EBB268",
        "regular-blue": "#3C6772",
        "f-white": "#FFF7E9",
        "t-pink": "#FDE3B5",
        "bg-main": "#2D061B",
        modal: "rgba(0, 0, 0, 0.62)",
        cardElFrom: "rgba(45, 6, 27, 0.18)",
        cardElTo: "rgb(45 6 27 / 85%)",
      },
      boxShadow: {
        "card-shadow":
          "inset 0px 0px 34.0148px rgba(255, 255, 255, 0.05), inset 0px 2.26765px 2.26765px rgba(255, 255, 255, 0.15)",
      },
    },
  },
  plugins: [
    plugin(function ({ addComponents }) {
      addComponents({
        ".btn": {
          display: "flex",
          flexDirection: "row",
          alignItems: "flex-start",
          padding: "20px 32px",
          gap: "10px",
          left: "1203px",
          top: "20px",
          background: "#EBB268",
          borderRadius: "199px",
          fontFamily: "Poppins",
          fontStyle: "normal",
          fontWeight: "700",
          fontSize: "18px",
          lineHeight: "22px",
          color: "#433E3E",
        },
        ".btn-second": {
          display: "flex",
          flexDirection: "row",
          alignItems: "flex-start",
          padding: "18px 30px",
          gap: "10px",
          left: "1203px",
          top: "20px",
          border: "4px solid #EBB268",
          borderRadius: "199px",
          fontFamily: "Poppins",
          fontStyle: "normal",
          fontWeight: "700",
          fontSize: "18px",
          lineHeight: "22px",
          color: "#433E3E",
        },
        ".btn-modal": {
          display: "flex",
          flexDirection: "row",
          alignItems: "flex-start",
          padding: "12px 16px",
          gap: "10px",
          left: "1203px",
          top: "20px",
          background: "#EBB268",
          borderRadius: "199px",
          fontFamily: "Poppins",
          fontStyle: "normal",
          fontWeight: "700",
          fontSize: "18px",
          lineHeight: "22px",
          color: "#433E3E",
        },
        ".btn-modal-second": {
          display: "flex",
          flexDirection: "row",
          alignItems: "flex-start",
          padding: "12px 16px",
          gap: "10px",
          left: "1203px",
          top: "20px",
          border: "4px solid #EBB268",
          borderRadius: "199px",
          fontFamily: "Poppins",
          fontStyle: "normal",
          fontWeight: "700",
          fontSize: "18px",
          lineHeight: "22px",
          color: "#EBB26",
        },
        ".btn-modal-send": {
          display: "flex",
          justifyContent: "center",
          flexDirection: "row",
          alignItems: "flex-start",
          padding: "12px 16px",
          gap: "10px",
          left: "1203px",
          top: "20px",
          background: "#EBB268",
          width: "100%",
          borderRadius: "199px",
          fontFamily: "Poppins",
          fontStyle: "normal",
          fontWeight: "700",
          fontSize: "18px",
          lineHeight: "22px",
          color: "#433E3E",
        },
      });
    }),
  ],
};
